/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartsPartIdRouteImport } from './routes/parts.$partId'

const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsPartIdRoute = PartsPartIdRouteImport.update({
  id: '/parts/$partId',
  path: '/parts/$partId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enquiries': typeof EnquiriesRoute
  '/inventory': typeof InventoryRoute
  '/parts/$partId': typeof PartsPartIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enquiries': typeof EnquiriesRoute
  '/inventory': typeof InventoryRoute
  '/parts/$partId': typeof PartsPartIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enquiries': typeof EnquiriesRoute
  '/inventory': typeof InventoryRoute
  '/parts/$partId': typeof PartsPartIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/enquiries' | '/inventory' | '/parts/$partId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/enquiries' | '/inventory' | '/parts/$partId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/enquiries'
    | '/inventory'
    | '/parts/$partId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EnquiriesRoute: typeof EnquiriesRoute
  InventoryRoute: typeof InventoryRoute
  PartsPartIdRoute: typeof PartsPartIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$partId': {
      id: '/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof PartsPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EnquiriesRoute: EnquiriesRoute,
  InventoryRoute: InventoryRoute,
  PartsPartIdRoute: PartsPartIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
